title: Heeyun KIM 김희연 # your name (or website title) here
logo: "/images/리온.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>EWHA WOMANS UNIVERSITY Electronical Engineering<br>
  Second description 
  <br>Email : eelinus@naver.com<br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
